### ISSUE TITLE
Error when re-running CI on PR: reference is not a tree

### ISSUE THREAD

**Issue by lovasoa** [actions/checkout#222]
Hello,
  When re-running failed tests on a PR in https://github.com/sql-js/sql.js/pull/388 , actions/checkout encountered the following error : 

```
 git checkout --progress --force 13088203ce13456b5da57c24664c2ff6f174dc2a
##[error]fatal: reference is not a tree: 13088203ce13456b5da57c24664c2ff6f174dc2a
##[error]Git checkout failed with exit code: 128
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.169.0/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```

**Comment by ericsciple** [comment]
Are you using `actions/checkout@v2` or `actions/checkout@v1`? This sounds like a race condition that was fixed in v2.

**Comment by lovasoa** [comment]
This error happened with `actions/checkout@v1`, indeed.

**Comment by ericsciple** [comment]
Yep this is fixed in `v2`. V2 fetches a specific SHA.

Whereas V1 fetched the ref (`refs/pull/#/merge`) and then tried to checkout the SHA. It's a race condition. A new push to the PR, causes the ref to point to a new merge commit. So the old SHA isn't in the history anymore when `refs/pull/#/merge` is fetched.

I'm going to add a troubleshooting doc. Will add a section for this issue.

**Comment by ericsciple** [comment]
It would also be great if the error were more actionable.

**Comment by ericsciple** [comment]
duplicate of this issue: https://github.com/actions/checkout/issues/23

**Comment by TomasHubelbauer** [comment]
FWIW the linked duplicate is closed, but this issue still reproduces in some cases, so it is good to have an open issue around.
